version: "3.3"

services:
  #  Create a service named db.
  db:
    restart: always
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can changes to something else.
    container_name: "postgres-server"
    #   Setup the username, password, and database name. You can changes these values.
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASS}"
      POSTGRES_DB: clientdb
    #   Maps port 54320 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    secrets:
      - source: db_password
        target: database_password_secret
      - source: db_user
        target: database_user_secret
        mode: 0440
    ports:
      - "7432:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data but you can changed it to something else.
#    volumes:
#      - ./postgres-data:/var/lib/postgresql/data
secrets:
  db_user:
    file: ./user.txt
  db_password:
    file: ./p-cred.txt
networks:
  default:
    external:
      name: microservice