version: '3.3'
services:
  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    restart: always
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
  zipkin:
    restart: always
    container_name: 'zipkin'
    image: openzipkin/zipkin
    ports:
      - '9411:9411'
    depends_on:
      - jaeger
networks:
  default:
    external:
      name: microservice