version: "3"
services:
  ms-clients:
    container_name: 'ms-clients'
    build:
      context: ../../ms-clients/.
      dockerfile: Dockerfile
    environment:
      EUREKA_URI: http://ms-registry:8761
      MS_CONFIG_SERVER: http://ms-config-properties:8088
      ARTIFACT: ms-clients
      VERSION: 1.0.0
      PORT: 9090
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DATABASE: jdbc:postgresql://postgres-server:5432/clientdb
      HOST_CACHE: redis-server
      HOST_ADMIN: http://ms-admin-server:9000
      HOST_TRACE: jaeger
      KAFKA_HOST: kafka-server:9092
      LOGSTASH: logstash:5044
    ports:
      - '9091:9091'
networks:
  default:
    external:
      name: microservice