version: "3"
services:
  ms-currency-transaction:
    container_name: 'ms-currency-transaction'
    build:
      context: ../../ms-currency-transaction/.
      dockerfile: Dockerfile
    environment:
      EUREKA_URI: http://ms-registry:8761
      MS_CONFIG_SERVER: http://ms-config-properties:8088
      ARTIFACT: ms-currency-transaction
      VERSION: 1.0.0
      PORT: 9095
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      URI_EVENT: http://ms-mediator-event:9545/ms-mediator-event/api/v1
      DATABASE: jdbc:postgresql://postgres-server:5432/rbacdb
      HOST_CACHE: redis-server
      HOST_ADMIN: http://ms-admin-server:9000
      HOST_TRACE: jaeger
      KAFKA_HOST: kafka-server:9092
    ports:
      - '9095:9095'
networks:
  default:
    external:
      name: microservice