version: "3"
services:
  ms-identity:
    container_name: 'ms-identity'
    build:
      context: ../../ms-identity/.
      dockerfile: Dockerfile
    environment:
      EUREKA_URI: http://ms-registry:8761
      MS_CONFIG_SERVER: http://ms-config-properties:8088
      ARTIFACT: ms-identity
      VERSION: 1.0.0
      PORT: 9093
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DATABASE: jdbc:postgresql://postgres-server:5432/rbacdb
      HOST_CACHE: redis-server
      HOST_ADMIN: http://ms-admin-server:9000
      HOST_TRACE: jaeger
      KAFKA_HOST: kafka-server:9092
    ports:
      - '9093:9093'
networks:
  default:
    external:
      name: microservice