version: "3"
services:
  ms-messaging:
    container_name: 'ms-messaging'
    build:
      context: ../../ms-messaging/.
      dockerfile: Dockerfile
    environment:
      EUREKA_URI: http://ms-registry:8761
      MS_CONFIG_SERVER: http://ms-config-properties:8088
      ARTIFACT: ms-mediator-event
      VERSION: 1.0.0
      PORT: 9001
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DATABASE: jdbc:postgresql://postgres-server:5432/rbacdb
      URI_EVENT: http://ms-mediator-event:9545/ms-mediator-event/api/v1
      URI_SENDGRID: http://ms-identity:9093/ms-identity/api/v1/
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_REPLAY: ${EMAIL_REPLAY}
      ACCESS_KEY: ${ACCESS_KEY}
      TEMPLATE_ID: ${TEMPLATE_ID}
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
      RABBITMQ_USR: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      HOST_CACHE: redis-server
      HOST_ADMIN: http://ms-admin-server:9000
      HOST_TRACE: jaeger
      KAFKA_HOST: kafka-server:9092
      MONGO_URI: mongo-server
      LOGSTASH: logstash:5044
    ports:
      - '9001:9001'
networks:
  default:
    external:
      name: microservice