version: "3"
services:
  ms-mediator-event:
    container_name: 'ms-mediator-event'
    build:
      context: ../../ms-mediator-event/.
      dockerfile: Dockerfile
    environment:
      EUREKA_URI: http://ms-registry:8761
      MS_CONFIG_SERVER: http://ms-config-properties:8088
      ARTIFACT: ms-mediator-event
      VERSION: 1.0.0
      PORT: 9545
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DATABASE: jdbc:postgresql://postgres-server:5432/rbacdb
      HOST_CACHE: redis-server
      HOST_ADMIN: http://ms-admin-server:9000
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      GOOGLE_CREDENTIALS: ${GOOGLE_CREDENTIALS}
      HOST_TRACE: jaeger
      KAFKA_HOST: kafka-server:9092
      LOGSTASH: logstash:5044
    ports:
      - '9545:9545'
networks:
  default:
    external:
      name: microservice