version: "3"
services:
  ms-registry:
    container_name: 'ms-registry'
    build:
      context: ../../ms-registry/.
      dockerfile: Dockerfile
    environment:
      - "EUREKA_URI=http://ms-registry:8761"
      - "MS_CONFIG_SERVER=http://ms-config-properties:8088"
      - "ARTIFACT=ms-registry"
      - "VERSION=1.0.0"
      - "PORT=9093"
      - "DATABASE=jdbc:postgresql://postgres-server:5432/rbacdb"
      - "HOST_CACHE=redis-server"
    ports:
      - '9093:9093'
networks:
  default:
    external:
      name: microservice