version: "3"
services:
  sub-currency-transaction:
    container_name: 'sub-currency-transaction'
    build:
      context: ../../sub-currency-transaction/.
      dockerfile: Dockerfile
    environment:
      EUREKA_URI: http://ms-registry:8761
      MS_CONFIG_SERVER: http://ms-config-properties:8088
      ARTIFACT: sub-currency-transaction
      URI_EVENT: http://ms-mediator-event:9545/ms-mediator-event/api/v1
      VERSION: 1.0.0
      PORT: 9096
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DATABASE: jdbc:postgresql://postgres-server:5432/rbacdb
      HOST_CACHE: redis-server
      HOST_ADMIN: http://ms-admin-server:9000
      HOST_TRACE: jaeger
      KAFKA_HOST: kafka-server:9092
      MONGO_URI: mongo-server
      RABBITMQ_HOST: rabbitmq-server
      RABBITMQ_PORT: 5672
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PWD: ${RABBITMQ_PWD}
    ports:
      - '9096:9096'
networks:
  default:
    external:
      name: microservice