global:
  scrape_interval:   10s # By default, scrape targets every 10 seconds.
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'appteam-monitor'
scrape_configs:
  - job_name: 'applicationX'
    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s
    # Path can be different depending on your Spring Boot configuration
    metrics_path: '/actuator/metrics'
    scheme: https
    # Disable tls check due to self signed certificates
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ['ms-identity:9093']
        labels:
          group: 'ms'
          application: 'ms-identity'
      - targets: ['api1.staging.somedomain.com','api2.staging.somedomain.com']
        labels:
          group: 'staging'
          application: 'app1'