server:
  port: ${PORT:9000}
#  servlet:
#    context-path: ms-admin-server
---
spring:
  application:
    name: ms-admin-server
---
info:
  project:
    version: 1.0.0
    name: ms-admin-server
    description: Microservice Server Admin
---
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      #base-path: /ms-admin-server
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - gateway
          - actuator
          - health
          - info
          - metrics
          - prometheus
          - instances
        exclude: