server:
  port: ${PORT:9090}
---
spring:
  application:
    name: ms-clients
---
info:
  project:
    version: 1.0.0
    name: ms-clients
    description: Microservice de clientes
---
spring:
  datasource:
    url: ${DATABASE:jdbc:postgresql://localhost:7432/clientdb}
    driverClassName: org.postgresql.Driver
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PWD:postgres}
    data: "classpath:init-data.sql"
    #schema: "classpath:create_schema.sql"
    initialization-mode: always
---
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
---
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      #base-path: /ms-clients
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - actuator
          - health
          - info
          - metrics
          - prometheus
        exclude:
---
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-server-connect-timeout-seconds: 30
    registryFetchIntervalSeconds: 10
  instance:
    preferIpAddress: false