server:
  port: ${PORT:8080}
---
spring:
  application:
    name: ms-gateway
---
info:
  project:
    version: 1.0.0
    name: ms-gateway
    description: Microservice Api Gateway
---
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
        exclude:
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: id-ms-customers
          uri: lb://MS-GESTION-INSTRUCTOR
          predicates:
            - Path=/api/v1/customers/**
          filters:
            - RewritePath=/ms-instructor/(?<path>.*), /$\{path}
        - id: id-albumes
          uri: https://jsonplaceholder.typicode.com/albums
          predicates:
            - Path=/albums
---
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-server-connect-timeout-seconds: 30
    registryFetchIntervalSeconds: 10
  instance:
    preferIpAddress: false