server:
  port: ${PORT:8080}
  servlet:
    context-path: ms-gateway
---
spring:
  application:
    name: ms-gateway
---
info:
  project:
    version: 1.0.0
    name: ms-gateway
    description: Microservice Api Gateway
---
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      #base-path: /ms-gateway
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - gateway
          - actuator
          - health
          - info
          - metrics
          - prometheus
        exclude:
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: id-albumes
          uri: https://jsonplaceholder.typicode.com/albums
          predicates:
            - Path=/albums
        - id: id-ms-currency-transaction
          uri: http://localhost:9095
          predicates:
            - Path=/ms-currency-transaction/**
        - id: id-ms-clients
          uri: http://localhost:9090
          predicates:
            - Path=/ms-clients/**
        - id: id-ms-identity
          uri: http://localhost:9093
          predicates:
            - Path=/ms-identity/**
        - id: id-ms-mediator-event
          uri: http://localhost:9545
          predicates:
            - Path=/ms-mediator-event/**
        - id: id-ms-messaging
          uri: http://localhost:9001
          predicates:
            - Path=/ms-messaging/**
        - id: id-ms-currency
          uri: http://localhost:9094
          predicates:
            - Path=/ms-currency/**
---
opentracing:
  jaeger:
    service-name: ms-gateway
    enabled: true
    udp-sender:
      host: ${HOST_TRACE:localhost}
      port: 6831
    log-spans: true