server:
  port: ${PORT:8080}
  servlet:
    context-path: ms-gateway
---
spring:
  application:
    name: ms-gateway
---
info:
  project:
    version: 1.0.0
    name: ms-gateway
    description: Microservice Api Gateway
---
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      #base-path: /ms-gateway
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - gateway
          - actuator
          - health
          - info
          - metrics
          - prometheus
        exclude:
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
#        - id: id-ms-customers
#          uri: lb://MS-GESTION-INSTRUCTOR
#          predicates:
#            - Path=/api/v1/customers/**
#          filters:
#            - RewritePath=/ms-instructor/(?<path>.*), /$\{path}
        - id: id-albumes
          uri: https://jsonplaceholder.typicode.com/albums
          predicates:
            - Path=/albums
        - id: id-ms-currency-transaction
          uri: http://localhost:9095/
          predicates:
            - Path=/ms-currency-transaction/**
---
opentracing:
  jaeger:
    service-name: ms-gateway
    enabled: true
    udp-sender:
      host: ${HOST_TRACE:localhost}
      port: 6831
    log-spans: true