server:
  port: ${PORT:9093}
---
spring:
  application:
    name: ms-identity
---
info:
  project:
    version: 1.0.0
    name: ms-identity
    description: Microservice de RBAC Login
---
spring:
  datasource:
    url: ${DATABASE:jdbc:postgresql://localhost:7432/rbacdb}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    data: "classpath:init-data.sql"
    #schema: "classpath:create_schema.sql"
    initialization-mode: always
---
spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
---
management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      #base-path: /ms-identity
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - actuator
          - health
          - info
          - metrics
          - prometheus
        exclude:
---
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-server-connect-timeout-seconds: 30
    registryFetchIntervalSeconds: 10
  instance:
    preferIpAddress: false
---
spring:
  cache:
    type: redis
  redis:
    host: ${HOST_CACHE:localhost}
    port: 6379
    connect-timeout: 30s
---
opentracing:
  jaeger:
    service-name: ms-identity
    enabled: true
    udp-sender:
      host: ${HOST_TRACE:localhost}
      port: 6831
    log-spans: true
---
spring:
  boot:
    admin:
      client:
        url: ${HOST_ADMIN:http://localhost:9000}
        enabled: true
        connect-timeout: 30s
        period: 30s