server:
  port: ${PORT:9001}
---
info:
  project:
    version: 1.0.0
    name: ms-messaging
    description: Microservice de clientes
---
management:
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      #base-path: /ms-clients
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - actuator
          - health
          - info
          - metrics
          - prometheus
        exclude:
---
sendgrid:
  queueName: hta.currency-exchange.transaction.messaging.subscriber
  from: ${EMAIL_FROM}
  reply: ${EMAIL_REPLAY}
  subject: "Envio de operacion de currency transaction"
  key: ${ACCESS_KEY}
  id: ${TEMPLATE_ID}
---
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USR:user}
    password: ${RABBITMQ_PWD:password}
    listener:
      direct:
        retry:
          max-attempts: 3
          max-interval: 30s
---
feign:
  client:
    config:
      event-service:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
---
event:
  uri: ${URI_EVENT:http://localhost:9545/ms-mediator-event/api/v1}
  app: hta
  origin: transaction
  destination: messaging
  domain: currency-exchange
---
spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017}
      database: ${MONGO_DATABASE:messagingdb}
---
spring:
  boot:
    admin:
      client:
        url: ${HOST_ADMIN:http://localhost:9000}
        enabled: true
        connect-timeout: 30s
        period: 30s