server:
  port: ${PORT:9545}
---
spring:
  application:
    name: ms-mediator-event
---
info:
  project:
    version: 1.0.0
    name: ms-mediator-event
    description: Microservice Api Event Mediator
---
management:
  endpoint:
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      #      base-path: /ms-mediator-event
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - actuator
          - health
          - info
          - metrics
          - prometheus
          - instances
        exclude:
---
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    eureka-server-connect-timeout-seconds: 30
    registryFetchIntervalSeconds: 10
    wait-time-in-ms-when-sync-empty: 3
  instance:
    preferIpAddress: false
---
spring:
  boot:
    admin:
      client:
        instance:
          health-url: /ms-mediator-event/health
---
spring:
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USR:user}
    password: ${RABBITMQ_PWD:password}
---
kafka:
  host: ${KAFKA_HOST:localhost:9092}
---
spring:
  cloud:
    gcp:
      pubsub:
        project-id: ${GOOGLE_PROJECT_ID}
        credentials:
          location: 'classpath:${GOOGLE_CREDENTIALS:/iam.json}'
      config:
        enabled: false
---
spring:
  boot:
    admin:
      client:
        url: ${HOST_ADMIN:http://localhost:9000}
        enabled: true
        connect-timeout: 30s
        period: 30s