server:
  port: ${PORT:8761}
---
spring:
  application:
    name: ms-registry
---
info:
  project:
    version: 1.0.0
    name: ms-registry
    description: Discovery Server Microservice
---
management:
  endpoints:
    web:
      base-path: /
      path-mapping:
        prometheus: /metrics
      exposure:
        include:
          - health
          - info
          - metrics
          - prometheus
        exclude:
---
eureka:
  instance:
    hostname: localhost
    statusPageUrlPath: http://localhost/info
    healthCheckUrlPath: http://localhost/health
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF