# Use root/example as user.txt/password credentials
version: '3.1'
services:
  mongo:
    image: mongo
    container_name: 'mongo-server'
    restart: always
    environment:
      MONGO_INITDB_DATABASE: messagingdb
    ports:
      - '27017-27019:27017-27019'
networks:
  default:
    external:
      name: microservice