spring:
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 8
        max-interval: 5000
  config:
    import: configserver:${MS_CONFIG_SERVER:http://localhost:8088}
  application:
    name: ms-currency
  profiles:
    active: ${MS_PROFILE:local}