spring:
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 5
  config:
    import: optional:configserver:${MS_CONFIG_SERVER:http://localhost:8088}
  application:
    name: sub-currency-transaction
  profiles:
    active: ${MS_PROFILE:local}